"""user table

Revision ID: 4081356520fe
Revises: 0bf7d32b2746
Create Date: 2020-04-21 20:26:11.695913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4081356520fe'
down_revision = '0bf7d32b2746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_img', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_img')
    # ### end Alembic commands ###
