"""user table

Revision ID: 7cf1dfd0e834
Revises: 4081356520fe
Create Date: 2020-04-23 13:03:56.947063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf1dfd0e834'
down_revision = '4081356520fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_stakeholder', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_stakeholder', 'user', ['stakeholder'], unique=1)
    # ### end Alembic commands ###
